In [1]:
import numpy as np

# Numpy Introduction

In [2]:
# Ways to build Array

# 1st Way
np_data = np.arange(1,11)

In [3]:
np_data = np.arange(1,51,3)

In [4]:
np_data

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [5]:
# 2nd Way
np_data = np.array([2,3,4,5,6,7,7,3,2,1,4,5])

In [6]:
np_data = np.array([[2,3,4],[5,6,7],[7,3,2],[1,4,5]])

In [7]:
np_data.shape

(4, 3)

In [8]:
np_data.ndim

2

In [9]:
np_data

array([[2, 3, 4],
       [5, 6, 7],
       [7, 3, 2],
       [1, 4, 5]])

In [10]:
np.rank(np_data)

C:\Users\asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  """Entry point for launching an IPython kernel.


2

In [11]:
np_data[0]

array([2, 3, 4])

In [12]:
np_data[3]

array([1, 4, 5])

In [13]:
np_data[0:2]

array([[2, 3, 4],
       [5, 6, 7]])

In [14]:
np_data

array([[2, 3, 4],
       [5, 6, 7],
       [7, 3, 2],
       [1, 4, 5]])

In [15]:
np_data[0][1]

3

In [16]:
np_data[1][1]

6

In [17]:
np_data[1:2,0:2]

array([[5, 6]])

In [18]:
np_data[0:2,0:2]

array([[2, 3],
       [5, 6]])

In [19]:
np_data[:,0:2]

array([[2, 3],
       [5, 6],
       [7, 3],
       [1, 4]])

In [20]:
np_data[1:3,1:3]

array([[6, 7],
       [3, 2]])

In [21]:
# 3rd Way
np_data = np.random.randint(100,200,10)

In [22]:
np_data

array([180, 125, 114, 153, 173, 170, 161, 183, 188, 152])

In [23]:
np_data = np.random.randn(5)

In [24]:
np_data

array([ 0.26260554, -0.0229553 ,  1.05436877,  0.08485082, -1.57665663])

In [25]:
np_data = np.random.randn(10,2)

In [26]:
np_data

array([[-0.55460097,  0.42430707],
       [ 0.50659211,  0.66769914],
       [ 2.25456473,  0.11227893],
       [-1.70531143,  0.29093609],
       [-0.53870779,  0.31344904],
       [ 1.96073426, -0.98981832],
       [ 0.28763207, -0.12782793],
       [ 0.41655625, -2.05699901],
       [ 1.26461176,  0.94277163],
       [-0.67463731, -0.69453337]])

In [27]:
np_data = np.random.randn(10,3)

In [28]:
np_data

array([[ 1.40098814,  1.93814209,  0.74019751],
       [-0.66875343,  1.07163788, -0.51257047],
       [ 0.17154264,  0.15696065,  0.63483478],
       [-0.45093821, -0.58640425, -0.72675989],
       [-0.4368149 , -1.18408396,  0.20673838],
       [-0.43890991,  0.37524031, -0.04483762],
       [ 1.54404038,  0.5003704 , -0.23856816],
       [-0.82347372,  2.30548994,  0.16976644],
       [ 1.42923751, -0.54109483, -1.26732188],
       [-1.36993957,  0.0283084 , -0.05844374]])

In [32]:
np_data = np.random.randn(10,2,2)

In [33]:
np_data.ndim

3

In [34]:
np_data

array([[[-0.37163496,  1.63933545],
        [-0.57227504, -0.12807008]],

       [[-0.79998097,  0.82039554],
        [-0.01275044,  0.08858299]],

       [[ 0.49578141, -0.02200687],
        [ 0.74283952,  0.12442577]],

       [[-1.44397244, -2.03224715],
        [ 0.05588212,  0.83370429]],

       [[ 0.51299807, -0.1856035 ],
        [ 0.16269913, -1.2236533 ]],

       [[ 1.30577347,  1.57018926],
        [ 0.30126308, -0.20067775]],

       [[ 0.51417162,  0.00426277],
        [ 0.39316787,  0.54301093]],

       [[-2.30441791, -0.93251954],
        [ 0.42281925,  0.4866154 ]],

       [[ 0.76126104,  0.7427844 ],
        [-0.17865034,  0.63275796]],

       [[-2.100039  ,  1.87806747],
        [-1.37572002, -0.35236953]]])

In [43]:
# 4th Way
# np_data = np.linspace(1,10)
np_data = np.linspace(1,10,12)

In [44]:
np_data

array([  1.        ,   1.81818182,   2.63636364,   3.45454545,
         4.27272727,   5.09090909,   5.90909091,   6.72727273,
         7.54545455,   8.36363636,   9.18181818,  10.        ])