In [1]:
import numpy as np

In [7]:
np_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

In [8]:
# np_arr.reshape(2,6)
np_arr.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
# np_arr.reshape(6,2)
np_arr = np.arange(1,25)

In [15]:
np_arr = np_arr.reshape(2,3,4)

In [16]:
np_arr.ndim

3

In [18]:
np_arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [19]:
np_arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [21]:
np_arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
np_arr.argmax()

23